/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as UnauthorizedImport } from "./routes/_unauthorized"
import { Route as AuthenticatedImport } from "./routes/_authenticated"
import { Route as AuthenticatedIndexImport } from "./routes/_authenticated/index"
import { Route as UnauthorizedAuthIndexImport } from "./routes/_unauthorized/auth/index"
import { Route as UnauthorizedAuthMfaImport } from "./routes/_unauthorized/auth/mfa"
import { Route as UnauthorizedAuthSignUpIndexImport } from "./routes/_unauthorized/auth/signUp/index"
import { Route as UnauthorizedAuthResetPasswordIndexImport } from "./routes/_unauthorized/auth/reset-password/index"
import { Route as UnauthorizedAuthSignUpConfirmEmailImport } from "./routes/_unauthorized/auth/signUp/confirmEmail"
import { Route as UnauthorizedAuthResetPasswordCodeImport } from "./routes/_unauthorized/auth/reset-password/code"

// Create/Update Routes

const UnauthorizedRoute = UnauthorizedImport.update({
  id: "/_unauthorized",
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  path: "/",
  getParentRoute: () => AuthenticatedRoute,
} as any)

const UnauthorizedAuthIndexRoute = UnauthorizedAuthIndexImport.update({
  path: "/auth/",
  getParentRoute: () => UnauthorizedRoute,
} as any)

const UnauthorizedAuthMfaRoute = UnauthorizedAuthMfaImport.update({
  path: "/auth/mfa",
  getParentRoute: () => UnauthorizedRoute,
} as any)

const UnauthorizedAuthSignUpIndexRoute =
  UnauthorizedAuthSignUpIndexImport.update({
    path: "/auth/signUp/",
    getParentRoute: () => UnauthorizedRoute,
  } as any)

const UnauthorizedAuthResetPasswordIndexRoute =
  UnauthorizedAuthResetPasswordIndexImport.update({
    path: "/auth/reset-password/",
    getParentRoute: () => UnauthorizedRoute,
  } as any)

const UnauthorizedAuthSignUpConfirmEmailRoute =
  UnauthorizedAuthSignUpConfirmEmailImport.update({
    path: "/auth/signUp/confirmEmail",
    getParentRoute: () => UnauthorizedRoute,
  } as any)

const UnauthorizedAuthResetPasswordCodeRoute =
  UnauthorizedAuthResetPasswordCodeImport.update({
    path: "/auth/reset-password/code",
    getParentRoute: () => UnauthorizedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_authenticated": {
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    "/_unauthorized": {
      preLoaderRoute: typeof UnauthorizedImport
      parentRoute: typeof rootRoute
    }
    "/_authenticated/": {
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    "/_unauthorized/auth/mfa": {
      preLoaderRoute: typeof UnauthorizedAuthMfaImport
      parentRoute: typeof UnauthorizedImport
    }
    "/_unauthorized/auth/": {
      preLoaderRoute: typeof UnauthorizedAuthIndexImport
      parentRoute: typeof UnauthorizedImport
    }
    "/_unauthorized/auth/reset-password/code": {
      preLoaderRoute: typeof UnauthorizedAuthResetPasswordCodeImport
      parentRoute: typeof UnauthorizedImport
    }
    "/_unauthorized/auth/signUp/confirmEmail": {
      preLoaderRoute: typeof UnauthorizedAuthSignUpConfirmEmailImport
      parentRoute: typeof UnauthorizedImport
    }
    "/_unauthorized/auth/reset-password/": {
      preLoaderRoute: typeof UnauthorizedAuthResetPasswordIndexImport
      parentRoute: typeof UnauthorizedImport
    }
    "/_unauthorized/auth/signUp/": {
      preLoaderRoute: typeof UnauthorizedAuthSignUpIndexImport
      parentRoute: typeof UnauthorizedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  AuthenticatedRoute.addChildren([AuthenticatedIndexRoute]),
  UnauthorizedRoute.addChildren([
    UnauthorizedAuthMfaRoute,
    UnauthorizedAuthIndexRoute,
    UnauthorizedAuthResetPasswordCodeRoute,
    UnauthorizedAuthSignUpConfirmEmailRoute,
    UnauthorizedAuthResetPasswordIndexRoute,
    UnauthorizedAuthSignUpIndexRoute,
  ]),
])

/* prettier-ignore-end */
